### ISSUE TITLE
Missing peer dependency

### ISSUE THREAD

**Issue by ebrpol** [marcuzy/tslint-origin-ordered-imports-rule#10]
Yarn 2 yields the following error:

➤ YN0002: │ tslint-origin-ordered-imports-rule@npm:1.2.1 doesn't provide typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev requested by tsutils@npm:2.29.0

See https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency for description of the problem.

Could you add typescript as a peer-dependency?

**Comment by marcuzy** [comment]
@ebrpol try the latest version (1.3.0-0)
