### ISSUE TITLE
Rule to check that there is an extra line between node_modules and custom imports

### ISSUE THREAD

**Issue by stas-kh** [marcuzy/tslint-origin-ordered-imports-rule#3]
Hi,

I've been using your package for more than half a year. Thanks for the work you do!

I am asking you to add an extra rule (possibly with false flag by default) that will check that there is an extra line between node_modules imports and our custom ones.

Example:
```
import { Router } from '@angular/router';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';

import { FormTypes } from '../../local/enums/form-types.enum';
```

**Comment by marcuzy** [comment]
Hi! It's a good idea. I'll add it in the immediate future.

**Comment by stas-kh** [comment]
Thank you! Looking forward to such feature.

**Comment by marcuzy** [comment]
It's taken a bit more time to take it from here 😀. I've just released a new version which supports blank lines:
```json
"rules": {
    "origin-ordered-imports": [ true, "one-blank-line" ]
}
```
It's also possible to require "no blank lines" or "at least one blank line", take a look at `src/originOrderedImportsRule.ts` to find out which options are supported.

I've also noticed it unluckily wasn't working with the latest TS, fixed that as well

**Comment by stas-kh** [comment]
Big thank you @marcuzy 
I will play with the rule tomorrow and let you know about the results! 
Appreciate the work you've done!

**Comment by stas-kh** [comment]
Hey @marcuzy 

I tested the new rule and found one issue, please correct me if I'm wrong.
We have the following rule in TSLint:
```
"max-line-length": [
  true,
  140
]
```
that restricts max length of a line to 140 symbols. Because of that rule some imports can be multilined with the following syntax:
```
import {
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  TemplateRef,
  ViewChild,
  ViewEncapsulation
} from '@angular/core';

import { UserInfo } from '../../local/interfaces/user-info.interface';
import { EmailInfo } from '../../../event/local/interfaces/email-info.interface';
```
In this case, the rule says there is an issue and doesn't let TSLint pass the linting

**Comment by marcuzy** [comment]
@stas-kh you're right. Fixed it.

**Comment by stas-kh** [comment]
Thank you, @marcuzy 
Now it works as expected!
