### ISSUE TITLE
Keep order for custom groups

### ISSUE THREAD

**Issue by xorik** [marcuzy/tslint-origin-ordered-imports-rule#8]
Hi! Thanks for the plugin!
But I'm not sure if it's desired behavior:
My rule:
```
    "origin-ordered-imports": [
      true,
      "no-blank-lines",
      [
        "^\\./",
        "^@/"
      ]
    ]
```
So I expect imports with prefix `./` go before imports with `@/`, but I can't see the warning in this case:
```
import { Module } from '@nestjs/common'
import { SomeModule } from '@/api/some.module'
import { PostController } from './post.controller'
```
I expect a warning that `./post.controller` should go before `@/api/some.module`

**Comment by marcuzy** [comment]
Hi! Your regexes contain errors:
`"^\\./"` should be `"^\\./.+"`
`"^@/"` sbould be `"^@/.+"`
Anyway, `"^\\./.+"` won't work here just because it conflicts with built-in "user" rule, so you could use something like this:
```json
[
  "user",
   "^@/.+"
]
```
Use the latest version of the lib, since 1.2.1 has some issues.

**Comment by xorik** [comment]
@marcuzy Thanks, it works!
